# Generated by Django 3.1.1 on 2020-09-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Dime time on which the object was last modified.', verbose_name='modified at')),
                ('license', models.CharField(max_length=10, verbose_name='License car')),
                ('manufactured', models.CharField(max_length=20, verbose_name='Manufactured car')),
                ('brand_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Brand type car')),
                ('model_year', models.PositiveIntegerField(default=2020)),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Color car')),
                ('seats', models.PositiveIntegerField(default=4)),
                ('is_available', models.BooleanField(default=True, help_text="Car is avaiable when it does not take a trip'", verbose_name='Available')),
                ('is_active', models.BooleanField(default=True, help_text="Bolean field to set if a car is active or not'", verbose_name='Available')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
